---
apiVersion: v1
kind: Namespace
metadata:
  annotations:
    openshift.io/description: This project contains all the resources related to
      the ACS operator
    openshift.io/display-name: ACS Operator
    argocd.argoproj.io/sync-wave: "-10"
  name: rhacs-operator
