---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  labels:
    app: rhacs
  name: rhacs
  namespace: openshift-gitops
spec:
  destination:
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    path: gitops-rhacs
    repoURL: https://github.com/alvarolop/ocp-rhacs
    targetRevision: main
    kustomize:
      components:
        - components/auth-openshift
        - components/consolelink
      patches:
        - target:
            kind: ConsoleLink
            name: stackrox-central
          patch: |-
            - op: replace
              path: /spec/href
              value: https://central-reencrypt-stackrox.apps.$CLUSTER_DOMAIN
        # - target:
        #     kind: OAuthClient
        #     name: rhacs-oidc
        #   patch: |-
        #     - op: replace
        #       path: /redirectURIs
        #       value:
        #         - https://central-reencrypt-stackrox.apps.$CLUSTER_DOMAIN/sso/providers/oidc/callback
        # - target:
        #     kind: Secret
        #     name: declarative-auth-openshift
        #   patch: |-
        #     apiVersion: v1
        #     kind: Secret
        #     metadata:
        #       name: declarative-auth-openshift
        #     stringData:
        #       auth-provider.yaml: |
        #         name: OpenShift OIDC
        #         minimumRole: None
        #         uiEndpoint: central-reencrypt-stackrox.apps.$CLUSTER_DOMAIN
        #         groups:
        #           - key: groups
        #             value: system:cluster-admins
        #             role: Admin
        #         oidc:
        #           issuer: https://oauth-openshift.apps.$CLUSTER_DOMAIN
        #           mode: auto
        #           clientID: rhacs-oidc
        #           clientSecret: CHANGEME-replace-with-random-secret
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
    syncOptions: []
