---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - sa-acs-enable-plugin.yaml
  - cr-acs-enable-plugin.yaml
  - crb-acs-enable-plugin.yaml
  - job-acs-enable-plugin.yaml
