---
apiVersion: v1
kind: Secret
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
  name: declarative-auth-openshift
  namespace: stackrox
type: Opaque
stringData:
  auth-provider.yaml: |
    name: OpenShift Auth
    minimumRole: None
    groups:
      - key: groups
        value: system:cluster-admins
        role: Admin
    openshift:
      enable: true
