---
kind: SecuredCluster
apiVersion: platform.stackrox.io/v1alpha1
metadata:
  name: local
  namespace: stackrox
  annotations:
    argocd.argoproj.io/sync-wave: "20"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  centralEndpoint: https://central.stackrox.svc:443
  clusterName: local
  monitoring:
    openshift:
      enabled: true
  auditLogs:
    collection: Auto
  admissionControl:
    enforcement: Enabled
    bypass: BreakGlassAnnotation
    replicas: 1
  scanner:
    analyzer:
      scaling:
        autoScaling: Disabled
        replicas: 1
    scannerComponent: AutoSense
  perNode:
    collector:
      collection: CORE_BPF
      imageFlavor: Regular
    taintToleration: TolerateTaints
