---
apiVersion: v1
kind: Namespace
metadata:
  annotations:
    openshift.io/description: This project contains the File Integrity Operator and its resources
    openshift.io/display-name: File Integrity Operator
    argocd.argoproj.io/sync-wave: "-10"
  labels:
    openshift.io/cluster-monitoring: "true"
    pod-security.kubernetes.io/enforce: privileged
  name: openshift-file-integrity
