---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: acs-cluster-registration
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: acs-cluster-registration
subjects:
  - kind: ServiceAccount
    name: acs-cluster-registration
    namespace: stackrox
